[package]
name = "simple-mcp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
mcp-sdk = { path = "mcp-sdk" }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
async-trait = "0.1"

[[bin]]
name = "simple-mcp-server"
path = "src/main.rs"